/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n9.0.2-22-g46d8f462ee-20261001"
#endif /* AVUTIL_FFVERSION_H */
