import { parseBuildJson } from './build-json.mjs';
import { readFile, stat } from 'node:fs/promises';
import path from 'node:path';

// 构建字段与旧 Unity CLI 参数保持同名。
export const enums = {
  outputKind: ['Player', 'Uaal', 'DedicatedServer'],
  buildType: ['UGC', 'Plot'], targetPlatform: ['Windows', 'Mac', 'Linux', 'Android', 'iOS'],
  architecture: ['Intel32', 'Intel64', 'Arm64', 'Universal'],
  buildVariant: ['None', 'China', 'Steam', 'IGP'], steamAppType: ['Demo', 'Body', 'PlayerTest'],
  outputMode: ['DirectFolder', 'AutoGeneratedSubfolder'], versionState: ['Release', 'Beta', 'Alpha', 'Dev'],
  scriptingBackend: ['Il2Cpp', 'Mono'], il2cppMode: ['Diagnostic', 'Release'],
  compressionMode: ['Default', 'LZ4', 'LZ4HC'], androidPackage: ['Apk', 'Aab', 'Both'],
};
const booleans = ['createVisualStudioSolution', 'useBugDataCollectionTool'];
const strings = ['outputDirectory', 'startScene'];
export const configKeys = ['schemaVersion', ...Object.keys(enums), ...booleans, ...strings, 'scenes'];
export const defaults = {
  schemaVersion: 1, outputKind: 'Player', buildType: 'UGC', targetPlatform: 'Windows',
  architecture: 'Intel64', buildVariant: 'None', steamAppType: 'Body',
  outputMode: 'DirectFolder', outputDirectory: 'Builds', versionState: 'Dev',
  scriptingBackend: 'Il2Cpp', compressionMode: 'LZ4HC', androidPackage: 'Both',
  createVisualStudioSolution: false,
};

// 校验配置，不将用户明确指定的不兼容组合静默改成其他目标。
export function validateConfig(raw) {
  if (!raw || Array.isArray(raw) || typeof raw !== 'object') throw Error('配置必须是 JSON 对象。');
  for (const key of Object.keys(raw))
    if (!configKeys.includes(key)) throw Error('未知配置字段：' + key);
  if (raw.schemaVersion !== 1) throw Error('schemaVersion 必须为 1。');
  if (!raw.il2cppMode) throw Error('必须明确指定 il2cppMode: Release 或 Diagnostic。');
  for (const [key, values] of Object.entries(enums))
    if (Object.hasOwn(raw, key) && !values.includes(raw[key])) throw Error('配置枚举无效：' + key);
  for (const key of booleans)
    if (Object.hasOwn(raw, key) && typeof raw[key] !== 'boolean') throw Error('配置必须是布尔值：' + key);
  for (const key of strings)
    if (Object.hasOwn(raw, key) && (typeof raw[key] !== 'string' || !raw[key].trim()))
      throw Error('配置必须是非空字符串：' + key);
  const c = { ...defaults, ...raw };
  const mobile = ['Android', 'iOS'].includes(c.targetPlatform);
  if (!Object.hasOwn(raw, 'architecture') && mobile) c.architecture = 'Arm64';
  c.useBugDataCollectionTool ??= c.outputKind === 'Player';
  const architectures = { Windows: ['Intel32', 'Intel64'], Mac: ['Intel64', 'Arm64', 'Universal'],
    Linux: ['Intel64'], Android: ['Arm64'], iOS: ['Arm64'] };
  if (!architectures[c.targetPlatform].includes(c.architecture)) throw Error('平台与架构不兼容。');
  if (mobile && (c.scriptingBackend !== 'Il2Cpp' || c.buildVariant === 'Steam' || c.createVisualStudioSolution))
    throw Error('移动平台需要 Il2Cpp，且不支持 Steam 渠道或 VS 工程。');
  if (c.outputKind === 'Uaal' && !mobile) throw Error('UAAL 仅支持 Android/iOS。');
  if (c.outputKind === 'DedicatedServer' &&
      (c.targetPlatform !== 'Windows' || c.architecture !== 'Intel64' || c.buildVariant !== 'None'))
    throw Error('DedicatedServer 需要 Windows Intel64 和 None 渠道。');
  if (c.outputKind !== 'Player' && c.useBugDataCollectionTool) throw Error('此产物必须关闭 Bug 数据采集。');
  if (c.outputKind !== 'Player' && (Object.hasOwn(raw, 'scenes') || Object.hasOwn(raw, 'startScene')))
    throw Error('此产物使用固定场景，不接受 scenes/startScene。');
  if (c.outputKind === 'Player') {
    if (!Array.isArray(c.scenes) || !c.scenes.length ||
        c.scenes.some(s => typeof s !== 'string' || !/^Assets\/.+\.unity$/.test(s) ||
          s.includes('\\') || s.split('/').includes('..') || s.includes(';')))
      throw Error('scenes 必须为 Assets/ 下的非空场景路径数组。');
    if (new Set(c.scenes).size !== c.scenes.length || !c.scenes.includes(c.startScene))
      throw Error('场景不能重复，startScene 必须在 scenes 中。');
  }
  return c;
}

// 项目相对路径统一从项目根目录解析，避免依赖调用终端位置。
export async function loadConfig(project, configFile, overrides = {}) {
  const raw = parseBuildJson(await readFile(path.resolve(project, configFile), 'utf8'));
  const config = validateConfig({ ...raw, ...overrides });
  config.outputDirectory = path.resolve(project, config.outputDirectory);
  const toProject = path.relative(config.outputDirectory, project);
  if (!toProject || (toProject !== '..' && !toProject.startsWith('..' + path.sep) && !path.isAbsolute(toProject)))
    throw Error('输出目录不能是工程目录或其祖先。');
  const protectedPaths = ['', 'Assets', 'Packages', 'ProjectSettings', 'Library', 'Temp', 'Tools', 'BuildConfigs'];
  for (const p of protectedPaths) {
    const root = path.resolve(project, p);
    const rel = path.relative(root, config.outputDirectory);
    if (!rel || (p && rel !== '..' && !rel.startsWith('..' + path.sep) && !path.isAbsolute(rel)))
      throw Error('输出目录不能覆盖工程或工程资源目录。');
  }
  if (path.parse(config.outputDirectory).root === config.outputDirectory) throw Error('输出目录不能是磁盘根目录。');
  for (const scene of config.scenes || [])
    if (!(await stat(path.join(project, scene))).isFile()) throw Error('场景文件不存在：' + scene);
  return config;
}

// Unity 的目标参数在加载项目之前生效。
export function buildTarget(config) {
  return { Windows: config.architecture === 'Intel32' ? 'Win' : 'Win64',
    Mac: 'OSXUniversal', Linux: 'Linux64', Android: 'Android', iOS: 'iOS' }[config.targetPlatform];
}
